apiVersion: v1
kind: Service
metadata:
  labels:
    type: source-deployment
  name: source-svc
spec:
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    type: source-pod
  type: LoadBalancer